version: '3.3'
services:
  prometheus:
    env_file: .env-ops
    image: ${USERNAME}/prometheus:latest
    ports:
      - '${PROMETHEUS_WEB}:9090'
    networks:
      - front_net
      - back_net

  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '${CADVISOR_WEB}:8080'
    networks:
      - front_net
      - back_net

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - ${GRAFANA_WEB}:3000
    networks:
      - front_net
      - back_net

  alertmanager:
    image: ${USERNAME}/alertmanager
    command:
      - '-config.file=/etc/alertmanager/config.yml'
    ports:
      - ${ALERTMANAGER_WEB}:9093
    networks:
      - front_net
      - back_net

  node-exporter:
    image: prom/node-exporter:v0.15.0
    deploy:
      mode: global
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - front_net
      - back_net

  mongodb-exporter:
    image: ${USERNAME}/mongodb_exporter
    networks:
      - back_net
    environment:
      - MONGODB_URL=mongodb://mongo_db:27017

volumes:
  post_db:
  grafana_data:


networks:
  back_net:
    ipam:
      driver: default
      config:
        - subnet: ${BACK_NET}
  front_net:
    ipam:
      driver: default
      config:
        - subnet: ${FRONT_NET}
