version: '3.3'
services:
  mongo_db:
    image: mongo:${VER_MONGO}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${VER_UI}
    ports:
      - ${PORT_UI_WEB}:${PORT_UI_DOCKER}/tcp
    networks:
      - front_net

  post:
    image: ${USERNAME}/post:${VER_POST}
    networks:
      - front_net
      - back_net

  comment:
    image: ${USERNAME}/comment:${VER_COMMENT}
    networks:
      - front_net
      - back_net

  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9090:9090'
    networks:
      - front_net
      - back_net

  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      - front_net
      - back_net

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - front_net
      - back_net

  alertmanager:
    image: ${USER_NAME}/alertmanager
    command:
      - '-config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:9093
    networks:
      - front_net
      - back_net

  node-exporter:
    image: prom/node-exporter:v0.15.0
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - front_net
      - back_net

  mongodb-exporter:
    image: ${USERNAME}/mongodb_exporter
    networks:
      - back_net
    environment:
      - MONGODB_URL=mongodb://mongo_db:27017

volumes:
  post_db:
  grafana_data:


networks:
  back_net:
    ipam:
      driver: default
      config:
        - subnet: ${BACK_NET}
  front_net:
    ipam:
      driver: default
      config:
        - subnet: ${FRONT_NET}
