# Alert for any instance that is unreachable for >5 minutes.
groups:
  - name: alert.rules
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute'
        summary: 'Instance {{ $labels.instance }} down'

    - alert: PutinAlert
      expr: putin_count > 0
      for: 1m
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} new title with about Putin'
        summary: 'Instance {{ $labels.instance }} new title with Putin'
