---
global:
  scrape_interval: '5s'

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
      - targets:
        - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:${PROMETHEUS_WEB}'

  - job_name: 'ui'
    static_configs:
      - targets:
        - 'ui:${PORT_UI_WEB}'

  - job_name: 'comment'
    static_configs:
      - targets:
        - 'comment:${COMMENT_WEB}'

  - job_name: 'node'
    static_configs:
      - targets:
        - 'node-exporter:9100'

  - job_name: 'mongodb-exporter'
    static_configs:
      - targets:
        - 'mongodb-exporter:9001'

  - job_name: 'cadvisor'
    static_configs:
    - targets:
      - 'cadvisor:${CADVISOR_WEB}'

  - job_name: 'post'
    static_configs:
      - targets:
        - 'post:${POST_PORT}'
